services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto_prisma_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    command: sh -c "mix deps.get && mix ecto.migrate && mix run priv/repo/seeds.exs && mix phx.server"
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
